environment:
  matrix:
    - PYTHON: "C:\\Python27"
      OUTPUT: "py27.exe"
    - PYTHON: "C:\\Python27-x64"
      OUTPUT: "py27-64.exe"
    - PYTHON: "C:\\Python35"
      OUTPUT: "py35.exe"
    - PYTHON: "C:\\Python35-x64"
      OUTPUT: "py35-64.exe"
    - PYTHON: "C:\\Python36"
      OUTPUT: "py36.exe"
    - PYTHON: "C:\\Python36-x64"
      OUTPUT: "py36-64.exe"

init:
  - SET PROJDIR=%cd%
  - SET ORIGPATH=%PATH%
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install pywin32 psutil six setuptools"
  - "python -m pip install pyinstaller"
  - mkdir c:\u
  - cd c:\u
  - curl -L -O "https://github.com/upx/upx/releases/download/v3.94/upx394w.zip"
  - unzip upx394w.zip
  - cd %PROJDIR%

build_script:
  - python modules_pyexe.py pyexe.py
  # Save the artifact immediately
  - appveyor PushArtifact pyexe.py
  - python -m PyInstaller --onefile pyexe.py --upx-dir C:\\u\\upx394w\\upx.exe --exclude-module FixTk --exclude-module tcl --exclude-module tk --exclude-module _tkinter --exclude-module tkinter --exclude-module Tkinter
  - cp dist\pyexe.exe %OUTPUT%
  # Save the artifact immediately
  - appveyor PushArtifact %OUTPUT%

test_script:
  - SET PATH=%ORIGPATH%
  - pip install pytest
  - "python -m pytest -l --exe=%OUTPUT%"

# artifacts:
#   - path: pyexe.py
#   - path: "%OUTPUT%"

deploy:
  - provider: GitHub
    tag: 'pyexe-latest'
    release: 'Release pyexe-latest'
    auth_token:
      secure: PGsGUDU6oqIy7zCyTMwIWlzf4TbJtuIgqmWb9ZLqNlM13AAaxWfDlzDlG+0CyHFx
    artifact: "%OUTPUT%"
    force_update: true
    on:
      branch: master

  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: Release $(appveyor_repo_tag_name)
    auth_token:
      secure: PGsGUDU6oqIy7zCyTMwIWlzf4TbJtuIgqmWb9ZLqNlM13AAaxWfDlzDlG+0CyHFx
    artifact: "%OUTPUT%"
    force_update: true
    on:
      appveyor_repo_tag: true
